@startuml

skinparam monochrome true
skinparam packageStyle rect
skinparam defaultFontName FG Virgil
skinparam shadowing false

class HttpServerAjax <<http server>>
class ViewBoardHistoryController <<application>>
class SessionManager
class BoardRepository <<repository>>
class BoardService <<service>>
class Board <<domain>>
class User <<domain>>

HttpServerAjax --> ViewBoardHistoryController : theController
HttpServerAjax --> SessionManager : sessionManager
SessionManager ..> User
ViewBoardHistoryController --> BoardService : boardService
BoardService --> BoardRepository : boardRepository
BoardRepository --> Board
BoardService --> Board : board

HttpServerAjax : viewBoardHistory()
SessionManager : getUserByToken()
ViewBoardHistoryController : viewBoardHistory()
BoardService : viewBoardHistoryUpdates()
Board : userHasPermission(User, AccessLevel)
BoardRepository : ofIdentity(Long)
BoardRepository : save(Board)


@enduml