@startuml "User and Course Aggregates"

hide methods

skinparam classAttributeIconSize 0

skinparam class {
    LifeLineBorderColor DodgerBlue
    LifeLineBackgroundColor APPLICATION
    BackgroundColor #D8F5FF
    ArrowColor DodgerBlue
    BorderColor DodgerBlue
}

skinparam packageStyle rectangle
skinparam card {
    LifeLineBorderColor DodgerBlue
    LifeLineBackgroundColor APPLICATION
    BackgroundColor #D8F5FF
    ArrowColor DodgerBlue
    BorderColor DodgerBlue
}


package UserAggregate{
    entity User <<entity>><<root>>

    card Email <<Value Object>>{
    }
    card Password <<Value Object>>{
    }
    card FullName <<Value Object>>{
    }
    card ShortName <<Value Object>>{
    }
    card Role <<Value Object>>{
    }

    User -- Email
    User -- Password
    User -- FullName
    User -- ShortName
    User -- Role

    note left of Role
         Can be one of the following:
            - Manager
            - Teacher
            - Student
    end note

}

package CourseAggregate{
    entity Course <<entity>><<root>>

    card Name <<Value Object>>{
    }
    card State <<Value Object>>{
    }
    card Description <<Value Object>>{
    }
    card Limit <<Value Object>>{
    }
    card Edition <<Value Object>>{
    }

    Course -- Name
    Course -- State
    Course -- Description
    Course -- Limit
    Course -- Edition

    note left of State
        Can be one of the following:
            - Open
            - Closed
    end note

    note left of Limit
        Each course as a lower
        and higher limit
        number of students
    end note
}

    User --> Course

@enduml