@startuml "Shared Boards"
left to right direction

hide methods

skinparam classAttributeIconSize 0

skinparam class {
    LifeLineBorderColor DodgerBlue
    LifeLineBackgroundColor APPLICATION
    BackgroundColor #D8F5FF
    ArrowColor DodgerBlue
    BorderColor DodgerBlue
}

skinparam packageStyle rectangle
skinparam card {
    LifeLineBorderColor DodgerBlue
    LifeLineBackgroundColor APPLICATION
    BackgroundColor #D8F5FF
    ArrowColor DodgerBlue
    BorderColor DodgerBlue
}

' PostIt
package PostItAggregate{
    entity PostIt <<Entity>><<root>>

    card PostItContent <<Value Object>>{
    }

    card PostItRow <<Value Object>>{
    }

    card PostItCol <<Value Object>>{
    }

    card PostItTimeStamp <<Value Object>>{
    }

    PostItContent <-- PostIt
    PostItRow <-- PostIt
    PostItCol <-- PostIt
    PostItTimeStamp <-- PostIt
}


' User
package UserAggregate{
    entity User <<Entity>><<root>>

    card ShortName <<Value Object>>{
    }

    card Email <<Value Object>>{
    }

    ShortName <-- User
    Email <-- User
    UpdateEventPostIt <-- User :interested in
}


' Board
package BoardAggregate{
    entity SharedBoard <<Entity>><<root>>
    
    card BoardTitle <<Value Object>>{
    }

    card BoardNRow <<Value Object>>{
    }

    card BoardNCol <<Value Object>>{
    }

    card BoardState <<Value Object>>{
    }

    card Title <<Value Object>>{
    }

    card Number <<Value Object>>{
    }

    BoardTitle <-- SharedBoard
    BoardNRow <-- SharedBoard
    BoardNCol <-- SharedBoard
    BoardState <-- SharedBoard

    entity BoardEntry <<Entity>>{
    }

    card BoardRow <<Value Object>>{
    }

    card BoardCol <<Value Object>>{
    }

    BoardEntry <-- SharedBoard
    BoardRow <-- BoardEntry
    BoardCol <-- BoardEntry
    Number <-- BoardRow
    Title <-- BoardCol
    Number <-- BoardCol
    Title <-- BoardRow


    entity BoardPermissions <<Entity>>

    card AccessLevel <<Value Object>>{
    }

    BoardPermissions <-- SharedBoard
    BoardPermissions --> User
    BoardPermissions --> AccessLevel
}

' Board Config
package BoardConfigAggregate{
    entity BoardCreateConfig <<Entity>><<root>>

    card BoardMaxRow <<Value Object>>{
    }

    card BoardMaxCol <<Value Object>>{
    }
    
    BoardCreateConfig --> BoardMaxRow
    BoardCreateConfig --> BoardMaxCol
}

' Relations
PostIt --> "1" User :owner
SharedBoard --> "1" User :owner
PostIt --> "1" SharedBoard :belongs
BoardCreateConfig <-- SharedBoard :has



' Events
card UpdateEventPostIt <<Event>>{
}

UpdateEventPostIt <-- PostIt :notify


@enduml
